eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 9030
spring:
  application:
    name: gotoali-service
  datasource:
    url: jdbc:mysql://rm-bp128giq0k0b9zi23qo.mysql.rds.aliyuncs.com:3306/test_groot
    username: groot
    password: Ilovebenz5e
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000

      stat-view-servlet:
        login-username: admin
        login-password: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000