eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 9020

spring:
  application:
    name: gotoali-controller

swagger:
  enabled: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000