eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8080

spring:
  application:
    name: gotoali-redis

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-wait: -1
        min-idle: 0
        max-idle: 8
        max-active: 8

swagger:
  enabled: true